-- Allowlist rows are data, not schema, and this repo is public: they are managed directly in
-- the Supabase SQL editor (`insert into allowed_emails (email, note) values (...)`), never
-- committed. This file once held an insert; it is kept (emptied) because the migration version
-- is already recorded as applied in production.
